SET SCHEMA PUBLIC
CREATE TABLE MENU_DETAIL (MENU_IDX NUMERIC(10), MENU_NAME VARCHAR(100), ORDER_IDX NUMERIC(10))

INSERT INTO MENU_DETAIL VALUES (1, '메인' , 1)
INSERT INTO MENU_DETAIL VALUES (1, 'ajax' , 2)
INSERT INTO MENU_DETAIL VALUES (1, '회원' , 3)

ALTER TABLE MENU_DETAIL ADD CONSTRAINT SYS_FK_95 FOREIGN KEY(MENU_IDX) REFERENCES MENU(MENU_IDX)